baseURL = "https://www.hailelagi.com/"
languageCode = "en-us"
title = "Haile Lagi"
theme = "etch"
pygmentsUseClasses = true
pygmentsCodeFences = true

[params]
  description = "A repository for my thoughts"
  copyright = "Copyright Â© 2021 Haile Lagi"
  dark = "off"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "work"
    name = "work"
    title = "work"
    url = "https://www.haile.tech"
    weight = 20

  [[menu.main]]
    identifier = "resume"
    name = "resume"
    title = "resume"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "resume"
    url = "/about/"
    weight = 20
